version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest_test
    networks:
      - nest
networks:
  nest:
    driver: bridge
    name: nest
